#!/bin/bash
# Get response times (RTs) from the subjects in patients.
# Uses the 'visualclosure-*-results.txt' files generated by 'visualclosure_parse_log.py'.
# by Chris Watson 11/15/2007

DIR=/raid2/fmri5/cardiac/patients
SUBJS='allison evan jacob jahaira jennifer jonathan joseph maia matthew meredith michelle sean'

# First, get all RTs for all subjects and place into a file.

for s in $SUBJS
    do
    awk 'NR == 52 , NR == 230 {print $2,$3,$5,$6}' $DIR/$s/raw-data/vi*.txt >> \
    $DIR/TOTAL_RTs.txt
done

# Next, separate control trials from task trials.
# Trials with stimulus ID starting 'CC' are controls.
# Change trials with rt= 0 to rt= 10s.

awk '/^C[0-9]+/ {print $2,$3,$4}' $DIR/TOTAL_RTs.txt >> $DIR/RTs_all.txt
rm $DIR/TOTAL_RTs.txt
sed -i 's/^0/10000/' $DIR/RTs_all.txt

# Now split the data into: all; all_correct/incorrect; 1trial_all/correct/incorrect; etc. 

DATA=$DIR/RTs_all.txt

awk '/True/ {print $1}' $DATA >> $DIR/RTs_all_correct.txt
awk '/False/ {print $1}' $DATA >> $DIR/RTs_all_incorrect.txt

awk '/1$/ {print $1,$2,$3}' $DATA >> $DIR/RTs_1trial_all.txt
awk '/True/ {print $1}' $DIR/RTs_1trial_all.txt >> $DIR/RTs_1trial_correct.txt
awk '/False/ {print $1}' $DIR/RTs_1trial_all.txt >> $DIR/RTs_1trial_incorrect.txt

awk '/2$/ {print $1,$2,$3}' $DATA >> $DIR/RTs_2trial_all.txt
awk '/True/ {print $1}' $DIR/RTs_2trial_all.txt >> $DIR/RTs_2trial_correct.txt
awk '/False/ {print $1}' $DIR/RTs_2trial_all.txt >> $DIR/RTs_2trial_incorrect.txt

awk '/3$/ {print $1,$2,$3}' $DATA >> $DIR/RTs_3trial_all.txt
awk '/True/ {print $1}' $DIR/RTs_3trial_all.txt >> $DIR/RTs_3trial_correct.txt
awk '/False/ {print $1}' $DIR/RTs_3trial_all.txt >> $DIR/RTs_3trial_incorrect.txt

cat $DATA | awk '{print $1}' > $DATA
cat $DIR/RTs_1trial_all.txt | awk '{print $1}' > $DIR/RTs_1trial_all.txt
cat $DIR/RTs_2trial_all.txt | awk '{print $1}' > $DIR/RTs_2trial_all.txt
cat $DIR/RTs_3trial_all.txt | awk '{print $1}' > $DIR/RTs_3trial_all.txt

wc -l $DIR/RT*
